---
name: docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - folder: v1.19
            tag: 1.19
            arm64: true
            arm: true
          - folder: v1.18.2
            tag: 1.18.2
            arm64: true
            arm: true
          - folder: v1.18.1
            tag: 1.18.1
            arm64: true
            arm: true
          - folder: v1.18
            tag: 1.18
            arm64: true
            arm: true
          - folder: v1.17.1
            tag: 1.17.1
            arm64: true
            arm: true
          - folder: v1.17
            tag: 1.17
            arm64: true
            arm: true
          - folder: v1.16.5
            tag: 1.16.5
            arm64: true
            arm: true
          - folder: v1.16.4
            tag: 1.16.4
            arm64: true
            arm: true
          - folder: v1.16.3
            tag: 1.16.3
            arm64: true
            arm: true
          - folder: v1.16.2
            tag: 1.16.2
            arm64: true
            arm: true
          - folder: v1.16.1
            tag: 1.16.1
            arm64: true
            arm: true
          - folder: v1.16
            tag: 1.16
            arm64: true
            arm: true
          - folder: v1.15.2
            tag: 1.15.2
            arm64: true
            arm: true
          - folder: v1.15.1
            tag: 1.15.1
            arm64: true
            arm: true
          - folder: v1.15
            tag: 1.15
            arm64: true
            arm: true
          - folder: v1.14.4
            tag: 1.14.4
            arm64: true
            arm: true
          - folder: v1.14.3
            tag: 1.14.3
            arm64: true
            arm: true
          - folder: v1.14.2
            tag: 1.14.2
            arm64: true
            arm: true
          - folder: v1.14.1
            tag: 1.14.1
            arm64: true
            arm: true
          - folder: v1.14
            tag: 1.14
            arm64: true
            arm: true
          - folder: v1.13.2
            tag: 1.13.2
            arm64: true
            arm: true
          - folder: v1.13.1
            tag: 1.13.1
            arm64: true
            arm: true
          - folder: v1.13
            tag: 1.13
            arm64: true
            arm: true
          - folder: v1.12.2
            tag: 1.12.2
            arm64: true
            arm: true
          - folder: v1.12.1
            tag: 1.12.1
            arm64: true
            arm: true
          - folder: v1.12
            tag: 1.12
            arm64: true
            arm: true
          - folder: v1.11.2
            tag: 1.11.2
            arm64: true
            arm: true
          - folder: v1.11.1
            tag: 1.11.1
            arm64: true
            arm: true
          - folder: v1.11
            tag: 1.11
            arm64: true
            arm: true
          - folder: v1.10.2
            tag: 1.10.2
            arm64: true
            arm: true
          - folder: v1.10.1
            tag: 1.10.1
            arm64: true
            arm: true
          - folder: v1.10
            tag: 1.10
            arm64: true
            arm: true
          - folder: v1.9.3
            tag: 1.9.3
            arm64: true
            arm: true
          - folder: v1.9.2
            tag: 1.9.2
            arm64: true
            arm: true
          - folder: v1.9.1
            tag: 1.9.1
            arm64: true
            arm: true
          - folder: v1.9
            tag: 1.9
            arm64: true
            arm: true
          - folder: v1.8.9
            tag: 1.8.9
            arm64: true
            arm: true
          - folder: v1.8.8
            tag: 1.8.8
            arm64: true
            arm: true
          - folder: v1.8.7
            tag: 1.8.7
            arm64: true
            arm: true
          - folder: v1.8.6
            tag: 1.8.6
            arm64: true
            arm: true
          - folder: v1.8.5
            tag: 1.8.5
            arm64: true
            arm: true
          - folder: v1.8.4
            tag: 1.8.4
            arm64: true
            arm: true
          - folder: v1.8.3
            tag: 1.8.3
            arm64: true
            arm: true
          - folder: v1.8.2
            tag: 1.8.2
            arm64: true
            arm: true
          - folder: v1.8.1
            tag: 1.8.1
            arm64: true
            arm: true
          - folder: v1.8
            tag: 1.8
            arm64: true
            arm: true
          - folder: v1.7.10
            tag: 1.7.10
            arm64: true
            arm: true
          - folder: latest
            tag: latest
            arm64: true
            arm: true

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            webhippie/minecraft-vanilla
            quay.io/webhippie/minecraft-vanilla
          labels: |
            org.opencontainers.image.vendor=Webhippie
            maintainer=Thomas Boerger <thomas@webhippie.de>

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Hub login
        id: login1
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Quay login
        id: login2
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build amd64
        id: amd64
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.version.folder }}/
          file: ${{ matrix.version.folder }}/Dockerfile.amd64
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            webhippie/minecraft-vanilla:${{ matrix.version.tag }}-amd64
            quay.io/webhippie/minecraft-vanilla:${{ matrix.version.tag }}-amd64

      - name: Build arm64
        id: arm64
        uses: docker/build-push-action@v3
        if: matrix.version.arm64
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.version.folder }}/
          file: ${{ matrix.version.folder }}/Dockerfile.arm64
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            webhippie/minecraft-vanilla:${{ matrix.version.tag }}-arm64
            quay.io/webhippie/minecraft-vanilla:${{ matrix.version.tag }}-arm64

      - name: Build arm
        id: arm
        uses: docker/build-push-action@v3
        if: matrix.version.arm
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.version.folder }}/
          file: ${{ matrix.version.folder }}/Dockerfile.arm
          platforms: linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            webhippie/minecraft-vanilla:${{ matrix.version.tag }}-arm
            quay.io/webhippie/minecraft-vanilla:${{ matrix.version.tag }}-arm

      - name: Hub manifest
        id: manifest1
        uses: actionhippie/manifest@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          template: webhippie/minecraft-vanilla:${{ matrix.version.tag }}-ARCH
          target: webhippie/minecraft-vanilla:${{ matrix.version.tag }}
          ignore_missing: true

      - name: Quay manifest
        id: manifest2
        uses: actionhippie/manifest@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          template: quay.io/webhippie/minecraft-vanilla:${{ matrix.version.tag }}-ARCH
          target: quay.io/webhippie/minecraft-vanilla:${{ matrix.version.tag }}
          ignore_missing: true

...
